### ISSUE TITLE
[Suggestion] Might try commandsPOST

### ISSUE THREAD

**Issue by AlexanderPico** [rosscm/fedup#3]
Hi. It's great to see RCy3 being used by another Bioconductor package :D

One suggestion. By using `commandsPOST` instead of `commandsGET` you can sometimes get more information back from Cytoscape, especially when there are errors. My general recommendation is to use POST by default and only use GET if POST doesn't work.

https://github.com/cytoscape/RCy3/blob/master/R/Commands.R#L330

Feel free to hit me up if you have any troubles with RCy3.

**Comment by rosscm** [comment]
Hi Alexander! Thanks for checking out the package 😃

I'm not able to get `commandsPOST` working in place of `commandsGET`.
(you'll have to excuse my naivety here since this is my first time using the CyREST Command API, or any API for that matter). 

My first `commandsGET` command builds the enrichment map from a temporary enrichment and GMT file like so:
```
resultsFile = "/var/folders/mh/_0z2r5zj3k75yhtgm6l7xy3m0000gn/T//RtmpNP9kHV/fedupResca8e1371a209.txt"
gmtFile = "/var/folders/mh/_0z2r5zj3k75yhtgm6l7xy3m0000gn/T//RtmpNP9kHV/pathwaysGMTca8e94506d8.gmt"

em_command <- paste(
    'enrichmentmap build analysisType="generic"',
    'networkName=', netName,
    "gmtFile=", gmtFile,
    "enrichmentsDataset1=", resultsFile,
    "pvalue=", 1,
    "qvalue=", 0.05,
    "similaritycutoff=", 0.375,
    "coefficients=", "COMBINED",
    "combinedConstant=", 0.5
)
 response <- commandsGET(em_command)
```

This works just fine. However, when replacing `commandsGET` with `commandsPOST` I get the following error:
```
Failed to execute: http://localhost:1234/v1/commands/enrichmentmap/build
Error: No enum constant org.baderlab.csplugins.enrichmentmap.model.EMCreationParameters.SimilarityMetric. COMBINED
```

Ok, I remove the `coefficients`  parameter and get a new error:
```
Failed to execute: http://localhost:1234/v1/commands/enrichmentmap/build
Error: /Applications/Cytoscape_v3.8.2/ /var/folders/mh/_0z2r5zj3k75yhtgm6l7xy3m0000gn/T/RtmpNP9kHV/pathwaysGMTca8e94506d8.gmt (No such file or directory)
```

The reason for using `commandsGET` is because I see it listed as a`GET` command in the CyREST Command API list. Is there another command I should be using instead to build the enrichment map? Or is there something else I'm missing here?

**Comment by AlexanderPico** [comment]
Ok. It's probably fine as-is. I've replaced most of my usage of `commandsGET` with `commandsPOST` to get more informative return values. But some cases still need GET. Maybe all the cases for enrichmentmap need GET?  Never mind :D

**Comment by rosscm** [comment]
Sounds good, thanks for the suggestion anyway! I'll be in touch if I have any other RCy3 questions 👍
